const productos = [
    {
        id: 1,
        productName: "FIFA",
        price: 900,
        quanty: 1,
        img: "/media/Fifa.webp",
    },
    {
        id: 2,
        productName: "CS-GO",
        price: 1100,
        quanty: 1,
        img: "/media/cs-go.webp",
    },
    {
        id: 3,
        productName: "Fortnite",
        price: 1500,
        quanty: 1,
        img: "/media/Fortnite.webp",
    },
    {
        id: 4,
        productName: "League of Legends",
        price: 1200,
        quanty: 1,
        img: "/media/lol.jpg",
    },
    {
        id: 5,
        productName: "Valorant",
        price: 1900,
        quanty: 1,
        img: "/media/Valorant.jpg",
    },
    {
        id: 6,
        productName: "Rocket League",
        price: 2500,
        quanty: 1,
        img: "/media/Rocket-League.jpg",
    },
    {
        id: 7,
        productName: "FIFA",
        price: 900,
        quanty: 1,
        img: "/media/Fifa.webp",
    },
    {
        id: 8,
        productName: "CS-GO",
        price: 1100,
        quanty: 1,
        img: "/media/cs-go.webp",
    },
    {
        id: 9,
        productName: "Fortnite",
        price: 1500,
        quanty: 1,
        img: "/media/Fortnite.webp",
    },
    {
        id: 10,
        productName: "League of Legends",
        price: 1200,
        quanty: 1,
        img: "/media/lol.jpg",
    },
    {
        id: 11,
        productName: "Valorant",
        price: 1900,
        quanty: 1,
        img: "/media/Valorant.jpg",
    },
    {
        id: 12,
        productName: "Rocket League",
        price: 2500,
        quanty: 1,
        img: "/media/Rocket-League.jpg",
    },
    {
        id: 13,
        productName: "League of Legends",
        price: 1200,
        quanty: 1,
        img: "/media/lol.jpg",
    },
    {
        id: 14,
        productName: "Valorant",
        price: 1900,
        quanty: 1,
        img: "/media/Valorant.jpg",
    },
    {
        id: 15,
        productName: "Rocket League",
        price: 2500,
        quanty: 1,
        img: "/media/Rocket-League.jpg",
    }
]